# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jxYqLbYE-aj9-s-vnSJhIPJdG2k3nHRF
"""

import pandas as pd
baza={
    " FISH": [  " Sodiqjonov Dilmurod"," Dadamahmudova Salimaxon" ," Hikmatov Ilg'orjon", "Muhammadov Ozodbek ", " Akbaraliyev Muhammadkarim" , "Rahmonaliyev Esonali",
              " Sobirov Olloberdi", " Abdusattorov Faxriyor"," Abduvoxidov Yodgorbek", " Ibrohimov Ozodbek"   ],
    " MANZILI ": [  " Farg'ona shahar"," Farg'ona shahar"," Farg'ona shahar"," Farg'ona shahar"," Farg'ona shahar"," Farg'ona shahar",
                 " Farg'ona shahar"," Farg'ona shahar"," Farg'ona shahar"," Farg'ona shahar"],
    " YOSHI": [ "19" , "19" ,"24", "19", "19" ," 19" ,"19" ,"19" ,"19" ,"19"   ],
    "O'QISH JOYI" : [  "TatuFF", "FarDu","TatuFF","TatuFF","TatuFF","TatuFF","TatuFF","TatuFF","TatuFF","TatuFF"],
    "Jinsi": [   "Erkak","Ayol" , "Erkak","Erkak","Erkak","Erkak","Erkak","Erkak","Erkak","Erkak"  ]
      }
db=pd.DataFrame(baza)
print (db)

filtr=db[db["Jinsi"] == "Ayol"]
print(filtr)

filtr=db[db[' YOSHI']>="21"]
print(filtr)

filtr1=db[db["O'QISH JOYI"]=="FarDu"]
print(filtr1)